package fr.formation.inti.entity;
// Generated 6 mai 2021 � 13:26:26 by Hibernate Tools 5.1.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * Employee generated by hbm2java
 */

@Entity
@Table(name = "rdv_salon")
public class RDV{

	private Integer id;
	private LocalDateTime start;
	private LocalDateTime end;
	private String title;
	
	private String state;
	private Double satisfactionRate;
	private String comment;
	
	private Employee emp;
	
	private Client client;
	

	public RDV() {
		
	}
	
	
	public RDV(LocalDateTime start, LocalDateTime end, String state) {
		super();
		this.start = start;
		this.end = end;
		this.state = state;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_rdv", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	public void setId(Integer rdvId) {
		this.id = rdvId;
	}

	
	@Column(name = "start")
	public LocalDateTime getStart() {
		return start;
	}

	public void setStart(LocalDateTime start) {
		this.start = start;
	}

	@Column(name = "end")
	public LocalDateTime getEnd() {
		return end;
	}

	public void setEnd(LocalDateTime end) {
		this.end = end;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}
	
	public void setTitle(String title) {
		this.title = title;
	}
	
	@Column(name = "state")
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "satisfaction_rate")
	public Double getSatisfactionRate() {
		return satisfactionRate;
	}

	public void setSatisfactionRate(Double satisfactionRate) {
		this.satisfactionRate = satisfactionRate;
	}

	@Column(name = "comment")
	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}
	
	@ManyToOne
	@JoinColumn(name = "id_employee", nullable = true)
	public Employee getEmp() {
		return emp;
	}

	public void setEmp(Employee emp) {
		this.emp = emp;
	}

	@ManyToOne
	@JoinColumn(name = "id_client", nullable = true)
	public Client getClient() {
		return client;
	}

	public void setClient(Client client) {
		this.client = client;
	}



	@Override
	public String toString() {
		return "RDV [id=" + id + ", start=" + start + ", end=" + end + ", title=" + title + "]";
	}
	
	
}
